apiVersion: v1
kind: Namespace
metadata:
  name: flink-fraud
---
apiVersion: v1
kind: Service
metadata:
  name: flink-jobmanager
  namespace: flink-fraud
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30080
  selector:
    app: flink
    component: jobmanager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-jobmanager
  namespace: flink-fraud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flink
      component: jobmanager
  template:
    metadata:
      labels:
        app: flink
        component: jobmanager
    spec:
      containers:
        - name: jobmanager
          image: flink:1.18-scala_2.12
          args: ["jobmanager"]
          ports:
            - containerPort: 8081
          env:
            - name: JOB_MANAGER_RPC_ADDRESS
              value: flink-jobmanager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-taskmanager
  namespace: flink-fraud
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flink
      component: taskmanager
  template:
    metadata:
      labels:
        app: flink
        component: taskmanager
    spec:
      containers:
        - name: taskmanager
          image: flink:1.18-scala_2.12
          args: ["taskmanager"]
          env:
            - name: JOB_MANAGER_RPC_ADDRESS
              value: flink-jobmanager
